import os
import pprint
import click
import pickle
from youtube import create_youtube_client
from time import time


def get_youtube_playlist_items(secrets_file, playlist_id):
    if os.path.exists("./.cache/youtubeapiclient.pkl"):
        with open("./.cache/youtubeapiclient.pkl", "rb") as inp:
            obj = pickle.load(inp)
            if obj.timestamp + 518400 > time():
                youtube = obj
            else: youtube = create_youtube_client(secrets_file)
    else: youtube = create_youtube_client(secrets_file)

    response = youtube.playlistItems().list(
        part="snippet,contentDetails",
        maxResults=50,
        playlistId=playlist_id
    ).execute()
    playlistItems = response['items']

    while response.get('nextPageToken'):
        response = youtube.playlistItems().list(
            part="snippet,contentDetails",
            maxResults=50,
            playlistId=playlist_id,
            pageToken=response['nextPageToken']
        ).execute()
        playlistItems = response['items'] + playlistItems

    return playlistItems


@click.command()
@click.option('--secret-file', default="client_secret.json", help="Path to GoogleAPI Credential File")
@click.argument('playlist_id')
def convert_yt_to_spotify(secret_file, playlist_id):
    yt_items = get_youtube_playlist_items(secret_file, playlist_id)

    spotify_search_queries = []

    # what's regex?
    # i fucking hate unicode
    remove_strings = ['MV', 'Official Music Video', 'Official Video', 'Official Lyric Video',
                      'Official HD Video', 'Official Audio', 'LyricVideo', 'MusicVideo', 'Audio',
                      'Video', 'HD', 'Original Song', 'HQ',
                      '()', '[]', '【 】', '（）', '( )', '[ ]', '【  】', '（ ）']
    remove_strings = remove_strings + [remove_string.upper() for remove_string in remove_strings]

    for yt_item in yt_items:
        description = yt_item['snippet']['description']
        if description == "This video is unavailable.": continue

        title = yt_item['snippet']['title']
        artist = yt_item['snippet']['videoOwnerChannelTitle']

        if description.find("Auto-generated by YouTube.") != -1:
            spotify_search_queries.append(f'{artist.replace(" - Topic", "")} {title}')
        else:
            for remove_string in remove_strings:
                title = title.replace(remove_string, "")
            spotify_search_queries.append(f'{title}')

    # if official audio, search query for spotify would be channel name + song name
    # else use video title with stripped info
